/** biome-ignore-all lint/style/useNamingConvention: ErrorCodes is a constant */
export const WorkerErrorCodes = {
  AUTH_VERSION_MISSING: "AUTH_VERSION_MISSING",
  AUTH_VERSION_UNKNOWN: "AUTH_VERSION_UNKNOWN",
  AUTH_PARAM_MISSING: "AUTH_PARAM_MISSING",
  AUTH_SIG_INVALID_HEX: "AUTH_SIG_INVALID_HEX",
  AUTH_SIG_MISMATCH: "AUTH_SIG_MISMATCH",
  AUTH_EXP_INVALID: "AUTH_EXP_INVALID",
  AUTH_EXPIRED: "AUTH_EXPIRED",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  TILE_TYPE_MISMATCH: "TILE_TYPE_MISMATCH",
  TILE_ZOOM_OUT_OF_RANGE: "TILE_ZOOM_OUT_OF_RANGE",
  ARCHIVE_NOT_FOUND: "ARCHIVE_NOT_FOUND",
  COMPRESSION_NOT_SUPPORTED: "COMPRESSION_NOT_SUPPORTED",
  GLYPH_NOT_FOUND: "GLYPH_NOT_FOUND",
  GLYPH_PATH_INVALID: "GLYPH_PATH_INVALID",
} as const;

export type WorkerErrorCode = (typeof WorkerErrorCodes)[keyof typeof WorkerErrorCodes];
